// <auto-generated />
namespace OrderManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialCreateforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialCreateforce));
        
        string IMigrationMetadata.Id
        {
            get { return "201606021359576_initialCreate-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
