// <auto-generated />
namespace OrderManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productId));
        
        string IMigrationMetadata.Id
        {
            get { return "201606101012253_productId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
