//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.OrderTransactions = new HashSet<OrderTransaction>();
        }
    
        public int InventoryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Employee_EmployeeId { get; set; }
        public Nullable<int> StoreLocation_StoreLocationId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual StoreLocation StoreLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTransaction> OrderTransactions { get; set; }
    }
}
