//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Customer_CustomerId { get; set; }
        public Nullable<int> LineItem_LineItemId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LineItem LineItem { get; set; }
    }
}
